### ISSUE TITLE
Commands missing parameters results in "Unknown command"

### ISSUE THREAD

**Issue by ApenJulius** [VetleViking/OS#15]
Giving more accurate responses to what kind of error it is, should provide a better user experience.
Current behaviour is:
```
> game
 Unknown command: game
```
Should be:
```
> game 
  Missing parameter [game name]
```

Edit:
Adding a SPACE after `game` gives proper response

```
> game 
  Please specify game
```

**Comment by VetleViking** [comment]
fixed now :)
